### ISSUE TITLE
[perf]: WebpackExtensionManifestPlugin.apply uses deprecated Tapable.plugin

### ISSUE THREAD

**Issue by mattduggan** [Scrum/webpack-extension-manifest-plugin#25]
See https://github.com/webpack/webpack/issues/6568#issuecomment-377491754

Stack trace where `process.traceDeprecation = true`
```bash
(node:70719) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at WebpackExtensionManifestPlugin.apply (~/dev/extension/node_modules/webpack-extension-manifest-plugin/lib/index.js:1:1253)
    at webpack (~/dev/extension/node_modules/webpack/lib/webpack.js:49:13)
```

**Comment by Scrum** [comment]
@mattduggan Hi, good catch 👍 , I will try to fix it soon
